### ISSUE TITLE
Set command doesn't merge content properly

### ISSUE THREAD

**Issue by josefbenjac** [contributte/neonizer#8]
### Use case: 

I got simple config file `parameters.local.neon`

```yaml
parameters:
    recaptcha:
        siteKey: ...
        secretKey: ...

    deploy:
        lastDeployAt: null
        lastCommit: null
        vcsUrl: ...
```

When I run set command,

```sh
composer set-config -- $(pwd)/app/config/parameters.local.neon --deploy.lastDeployAt=$DATE --deploy.lastCommit=$COMMIT
```

result is

```yaml
parameters:
    deploy:
        lastDeployAt: ...
        lastCommit: ...
```

I think problem is in array_merge function in `Contributte\Neonizer\TaskSet:80`.
